PACKAGE_NAME="minifuse"
PACKAGE_VERSION="WILL_BE_REPLACED"
MAKE[0]="make KERNELRELEASE=$kernelver"
CLEAN="make clean"
BUILT_MODULE_NAME[0]="minifuse"
DEST_MODULE_LOCATION[0]="/extramodules"
AUTOINSTALL="yes"
